"""Add projects

Revision ID: 3f893d4d04c4
Revises: 7bea853fded0
Create Date: 2021-06-12 13:37:44.384112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f893d4d04c4'
down_revision = '7bea853fded0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('created_dt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_user_id', 'name')
    )
    op.add_column('daily_todo_lists', sa.Column('project_id', sa.Integer(), nullable=True))
    op.drop_constraint('daily_todo_lists_user_id_for_day_key', 'daily_todo_lists', type_='unique')
    op.create_unique_constraint('daily_todo_lists_project_id_for_day_key', 'daily_todo_lists', ['project_id', 'for_day'])
    op.create_foreign_key('daily_todo_lists_project_id_fkey', 'daily_todo_lists', 'projects', ['project_id'], ['id'])
    op.add_column('todo_item_log_messages', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_foreign_key('todo_item_log_messages_project_id_fkey', 'todo_item_log_messages', 'projects', ['project_id'], ['id'])
    op.add_column('todo_items', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_foreign_key('todo_items_project_id_fkey', 'todo_items', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('todo_items_project_id_fkey', 'todo_items', type_='foreignkey')
    op.drop_column('todo_items', 'project_id')
    op.drop_constraint('todo_item_log_messages_project_id_fkey', 'todo_item_log_messages', type_='foreignkey')
    op.drop_column('todo_item_log_messages', 'project_id')
    op.drop_constraint('daily_todo_lists_project_id_fkey', 'daily_todo_lists', type_='foreignkey')
    op.drop_constraint('daily_todo_lists_project_id_for_day_key', 'daily_todo_lists', type_='unique')
    op.create_unique_constraint('daily_todo_lists_user_id_for_day_key', 'daily_todo_lists', ['user_id', 'for_day'])
    op.drop_column('daily_todo_lists', 'project_id')
    op.drop_table('projects')
    # ### end Alembic commands ###
