"""Delete bot settings

Revision ID: 45e7f823087b
Revises: 3f893d4d04c4
Create Date: 2021-06-12 14:03:29.978237

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '45e7f823087b'
down_revision = '3f893d4d04c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bot_settings')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_settings',
    sa.Column('section', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('content', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('section', name='bot_settings_pkey')
    )
    # ### end Alembic commands ###
