"""Add task statuses

Revision ID: 5ccb02f48d7b
Revises: e411f80b8ed5
Create Date: 2021-06-14 01:26:41.399080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ccb02f48d7b'
down_revision = 'e411f80b8ed5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('status', sa.String(length=32), nullable=True))
    op.drop_column('items_lists', 'for_day')
    op.execute("UPDATE items SET status = 'active';")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items_lists', sa.Column('for_day', sa.DATE(), autoincrement=False))
    op.drop_column('items', 'status')
    # ### end Alembic commands ###
