"""Log messages for todo items

Revision ID: 8d2d343ae2c1
Revises: 6ac1fec94d3b
Create Date: 2021-05-28 09:07:24.123260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d2d343ae2c1'
down_revision = '6ac1fec94d3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo_item_log_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('todo_item_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_dt', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['todo_item_id'], ['todo_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todo_item_log_messages')
    # ### end Alembic commands ###
