"""Initial cretate tables: users and todo lists

Revision ID: 6ac1fec94d3b
Revises: 
Create Date: 2021-05-21 17:58:05.938184

"""
from alembic import op
import sqlalchemy as sa
from dateutil.relativedelta import MO, TU, WE, TH, FR
from auxy.models import BotSettings


# revision identifiers, used by Alembic.
revision = '6ac1fec94d3b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_settings',
    sa.Column('section', sa.String(length=64), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('section')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('username', sa.String(length=256), nullable=True),
    sa.Column('first_name', sa.String(length=256), nullable=True),
    sa.Column('last_name', sa.String(length=256), nullable=True),
    sa.Column('lang', sa.String(length=64), nullable=True),
    sa.Column('joined_dt', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_todo_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_dt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('for_day', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'for_day')
    )
    op.create_table('todo_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_dt', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_in_list',
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('list_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['todo_items.id'], ),
    sa.ForeignKeyConstraint(['list_id'], ['daily_todo_lists.id'], )
    )

    # default configuration (before becoming highly configurable by user)
    op.bulk_insert(BotSettings.__table__, [
        {
            'section': 'workday_begin',
            'content': {
                'reminder_timings': {
                    MO.weekday: {'hour': 9, 'minute': 0, 'second': 0, 'microsecond': 0},
                    TU.weekday: {'hour': 9, 'minute': 0, 'second': 0, 'microsecond': 0},
                    WE.weekday: {'hour': 9, 'minute': 0, 'second': 0, 'microsecond': 0},
                    TH.weekday: {'hour': 9, 'minute': 0, 'second': 0, 'microsecond': 0},
                    FR.weekday: {'hour': 9, 'minute': 0, 'second': 0, 'microsecond': 0},
                }
            }
        }, {
            'section': 'workday_end',
            'content': {
                'reminder_text': 'Рабочий день подходит к концу, быть может пора уже закругляться?\n'
                                 'Но перед тем, как закончить, пожалуйста, '
                                 'составьте план на завтра и пришлите его мне.\n'
                                 'Утром я напомню о том, что вы собирались сделать.',
                'reminder_timings': {
                    MO.weekday: {'hour': 18, 'minute': 30, 'second': 0, 'microsecond': 0},
                    TU.weekday: {'hour': 17, 'minute': 30, 'second': 0, 'microsecond': 0},
                    WE.weekday: {'hour': 16, 'minute': 30, 'second': 0, 'microsecond': 0},
                    TH.weekday: {'hour': 18, 'minute': 30, 'second': 0, 'microsecond': 0},
                    FR.weekday: {'hour': 16, 'minute': 0, 'second': 0, 'microsecond': 0},
                },
            }
        }
    ])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_in_list')
    op.drop_table('todo_items')
    op.drop_table('daily_todo_lists')
    op.drop_table('users')
    op.drop_table('bot_settings')
    # ### end Alembic commands ###
